// Generated by https://quicktype.io

export interface Follower {
	login: string
	id: number
	node_id: string
	avatar_url: string
	gravatar_id: string
	url: string
	html_url: string
	followers_url: string
	following_url: string
	gists_url: string
	starred_url: string
	subscriptions_url: string
	organizations_url: string
	repos_url: string
	events_url: string
	received_events_url: string
	type: UserType
	site_admin: boolean
}

export enum UserType {
	User = 'User',
}

export async function getFollowers(username: string): Promise<Follower[]> {
	return await fetch(`https://api.github.com/users/${username}/followers`, {
		headers: {
			Authorization: `token ${process.env.GITHUB_TOKEN}`,
		},
	}).then(res => res.json() as Promise<Follower[]>)
}

export async function getFollowing(username: string): Promise<Follower[]> {
	return await fetch(`https://api.github.com/users/${username}/following`, {
		headers: {
			Authorization: `token ${process.env.GITHUB_TOKEN}`,
		},
	}).then(res => res.json() as Promise<Follower[]>)
}
